# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pjr/eclipse-workspace/OGN-Flogger-V5.0/src/../data/flogger_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 441)
        self.AboutgroupBox = QtWidgets.QGroupBox(Form)
        self.AboutgroupBox.setGeometry(QtCore.QRect(20, 20, 431, 391))
        self.AboutgroupBox.setStyleSheet("background-color: rgb(179, 255, 180);")
        self.AboutgroupBox.setTitle("")
        self.AboutgroupBox.setObjectName("AboutgroupBox")
        self.Aboutlabel = QtWidgets.QLabel(self.AboutgroupBox)
        self.Aboutlabel.setGeometry(QtCore.QRect(10, 20, 402, 381))
        self.Aboutlabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Aboutlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Aboutlabel.setObjectName("Aboutlabel")
        self.OkpushButton = QtWidgets.QPushButton(self.AboutgroupBox)
        self.OkpushButton.setGeometry(QtCore.QRect(280, 350, 109, 26))
        self.OkpushButton.setStyleSheet("border-color: rgb(255, 55, 78);\n"
"background-color: rgb(0, 255, 0);")
        self.OkpushButton.setObjectName("OkpushButton")

        self.retranslateUi(Form)
        self.OkpushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "About OGN Flight Logger"))
        self.Aboutlabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">OGN Flogger, realtime logging of Flarm signals</span>.</p><p><span style=\" font-weight:600;\">Designer</span>: Peter J Robinson</p><p><span style=\" font-weight:600;\">Graphics</span>: Adrian Melia</p><p><span style=\" font-weight:600;\">Data Source</span>: Open Glider Network (OGN)</p><p><span style=\" font-weight:600;\">Licences</span>: </p><p>Data - Used under the terms of ODbL</p><p>Code - GNU GENERAL PUBLIC LICENSE, Version 3 </p><p><span style=\" font-weight:600;\">Coordinates by</span>: OGN Nominatim Service </p><p>Developed using Eclipse Neon 3</p><p>UI developed using Qt Designer</p><p>Splash screen courtesy of OGN</p></body></html>"))
        self.OkpushButton.setText(_translate("Form", "OK"))
