# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pjr/eclipse-workspace/OGN-Flogger-V5.0/src/../data/flogger_no_flights.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(461, 187)
        self.NoFlightsgroupBox = QtWidgets.QGroupBox(Form2)
        self.NoFlightsgroupBox.setGeometry(QtCore.QRect(20, 20, 431, 151))
        self.NoFlightsgroupBox.setStyleSheet("background-color: rgb(179, 255, 180);")
        self.NoFlightsgroupBox.setTitle("")
        self.NoFlightsgroupBox.setObjectName("NoFlightsgroupBox")
        self.No_flights_label = QtWidgets.QLabel(self.NoFlightsgroupBox)
        self.No_flights_label.setGeometry(QtCore.QRect(10, 0, 402, 91))
        self.No_flights_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.No_flights_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.No_flights_label.setObjectName("No_flights_label")
        self.NoFlightsOkButton = QtWidgets.QPushButton(self.NoFlightsgroupBox)
        self.NoFlightsOkButton.setGeometry(QtCore.QRect(300, 100, 109, 26))
        self.NoFlightsOkButton.setStyleSheet("border-color: rgb(255, 55, 78);\n"
"background-color: rgb(0, 255, 0);")
        self.NoFlightsOkButton.setObjectName("NoFlightsOkButton")
        self.actionNFWOk = QtWidgets.QAction(Form2)
        self.actionNFWOk.setObjectName("actionNFWOk")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "About OGN Flight Logger"))
        self.No_flights_label.setText(_translate("Form2", "<html><head/><body><p align=\"center\"><br/><span style=\" font-size:14pt;\">No Flights Today</span></p></body></html>"))
        self.NoFlightsOkButton.setText(_translate("Form2", "OK"))
        self.actionNFWOk.setText(_translate("Form2", "&Action No Flight Ok"))
